import { ScentEntry } from "@/lib/types";

export const scentsTitle = "气味收藏：香气与季节";
export const scentsSubtitle = "Scent Journal";
export const scentsQuote =
  "收集并记录不同气味带来的空间感与记忆：从花香到木香，从清新到沉稳，从季节变化到时光流逝。";

export const SEASONS = ["春", "夏", "秋", "冬", "四季"] as const;
export const SCENES = ["通勤", "散步", "夜晚", "室内", "雨天"] as const;
export const FAMILIES = ["花香", "木质", "果香", "绿叶"] as const;
export const MOODS = [
  "干净",
  "放松",
  "温柔",
  "安定",
  "克制",
  "锐利",
  "治愈",
  "稳重",
] as const;

export const scentEntries: ScentEntry[] = [
  {
    id: "macedonia",
    name: "Macedonia",
    brand: "My Only Fragrance",
    year: "2025",
    concentration: "EDT",
    family: ["果香", "木质"],
    topNotes: ["佛手柑", "青苹果", "柠檬皮"],
    middleNotes: ["白玫瑰", "白麝香", "淡琥珀"],
    baseNotes: ["雪松木", "白麝香", "淡琥珀"],
    tags: ["干净", "自然", "通透", "空气感"],
    season: ["四季", "秋"],
    scene: ["通勤", "散步"],
    mood: ["放松", "平静","治愈"],
    longevity: 5,
    sillage: 4,
    liking: 5,
    text: "佛手柑与青苹果在开场带来清亮通透的果绿气息，像晨光穿过树叶时的第一口空气。随后柔和的白玫瑰与绿叶感缓缓浮现，让香气变得温润而自然。尾调的雪松木与白麝香轻轻铺展开来，干净、安静，仿佛阳光晒过的木地板，带着让人慢下来的温度。",
    shortFeeling: "像清晨森林里的空气，干净又温柔。",
    sceneMemory: "秋天在公园散步时的微风",
    memoryAnchor: "京都的冬天，清冷的空气与历史悠久的街道",
    imageSrc: "/images/perfume/macedonia.webp",
    featured: true,
  },
  {
    id: "english-pear-and-freesia",
    name: "English Pear & Freesia",
    brand: "Jo Malone",
    year: "2024",
    concentration: "EDC",
    family: ["果香", "花香", "木质"],
    topNotes: ["皇帝梨", "香瓜"],
    middleNotes: ["小苍兰", "玫瑰"],
    baseNotes: ["广藿香", "大黄", "麝香","琥珀"],
    tags: ["梨香", "小苍兰", "秋意", "干净"],
    season: ["春", "夏", "秋"],
    scene: ["通勤", "室内"],
    mood: ["温柔", "安定"],
    longevity: 2,
    sillage: 2,
    liking: 5,
    text: "英国梨的清甜在开场显得明亮而湿润，像雨后空气里带着果香的微凉气息。小苍兰与玫瑰在中调铺开柔软的花香层次，让香气变得轻盈而通透。尾调的麝香与琥珀轻轻收束整体轮廓，使这份清新多了一层温暖的深度，安静却耐闻。",
    shortFeeling: "像秋天午后下过雨的窗台",
    sceneMemory: "深秋雨后的图书馆",
    memoryAnchor: "新西兰冬天的雨后，带着些许泥土气息的街道",
    imageSrc: "/images/perfume/english_pear_and_freesia.webp",
  },
  {
    id: "chance-eau-tendre",
    name: "Chance Eau Fraiche",
    brand: "Chanel",
    year: "2025",
    concentration: "EDT",
    family: ["花香"],
    topNotes: ["柠檬", "雪松","香橼"],
    middleNotes: ["茉莉", "粉红胡椒", "凤眼兰"],
    baseNotes: ["广藿香", "麝香", "鸢尾花","香根草","柚木","琥珀"],
    tags: ["粉感", "干净","清新"],
    season: ["春", "四季"],
    scene: ["通勤", "室内"],
    mood: ["干净", "温柔"],
    longevity: 5,
    sillage: 4,
    liking: 4,
    text: "绿邂逅以清亮的柠檬气息开启，像清晨第一缕干净的阳光。茉莉在中调带来柔和而圆润的花香，却始终保持通透与克制，仿佛只是空气中一瞬掠过的香气。广藿香与麝香在尾调悄然铺陈，使整体变得干净而稳定，如白衬衫贴近肌肤时的安心感。",
    shortFeeling: "白衬衫与春日晨光",
    sceneMemory: "清晨出门，空气里的露水与花香交织",
    memoryAnchor: "每当清冷的早晨总会想起的味道",
    imageSrc: "/images/perfume/chance.webp",
  },
  {
    id: "wild-bluebell",
    name: "Wild Bluebell",
    brand: "Jo Malone",
    year: "2025",
    concentration: "EDC",
    family: ["绿叶", "花香"],
    topNotes: ["风铃草", "公丁香","露珠","绿叶"],
    middleNotes: ["桃子", "柿子"],
    baseNotes: ["脂粉", "麝香"],
    tags: ["透明", "林间", "皂感"],
    season: ["春", "夏"],
    scene: ["通勤", "室内"],
    mood: ["干净", "松弛"],
    longevity: 2,
    sillage: 4,
    liking: 3,
    text: "蓝风铃像一阵穿过树林的微风，带着清晨露水般的透明气息。绿叶与花香在空气中轻轻浮动，仿佛阳光洒在潮湿的土地与蓝色小花之间。整个香气始终轻盈而干净，没有刻意的浓度，只留下自然流动的清新感。",
    shortFeeling: "初夏树林间的一片蓝色",
    sceneMemory: "清晨散步时",
    memoryAnchor: "等待时间的镌刻",
    imageSrc: "/images/perfume/wild_bluebell.webp",
  },
  {
    id: "english-oak-and-hazelnut",
    name: "English Oak & Hazelnut",
    brand: "Jo Malone",
    year: "2026",
    concentration: "EDC",
    family: ["木质"],
    topNotes: ["榛子"],
    middleNotes: ["雪松"],
    baseNotes: ["橡木"],
    tags: ["木质", "榛果", "温暖", "秋冬"],
    season: ["秋", "冬"],
    scene: ["室内", "夜晚"],
    mood: ["安定", "克制"],
    longevity: 2,
    sillage: 3,
    liking: 4,
    text: "榛子的开场带来柔和而饱满的木质气息，没有甜腻感，反而显得温润而安静。中调的雪松逐渐铺开干净的木香空间，像阳光落在室内木质家具上的温度。尾调的橡木让整体变得柔和而沉稳，营造出一种适合慢下来的安定氛围。",
    shortFeeling: "像是坐在壁炉旁的沙发上，温暖又舒适。",
    sceneMemory: "秋夜室内，窗外在下雨",
    memoryAnchor: "等待时间的镌刻",
    imageSrc: "/images/perfume/english_oak_and_hazelnut.webp",
  },
  {
    id: "honeysuckle-and-davana",
    name: "Honeysuckle & Davana",
    brand: "Jo Malone",
    year: "2025",
    concentration: "EDC",
    family: ["花香"],
    topNotes: ["印蒿"],
    middleNotes: ["忍冬", "橙花"],
    baseNotes: ["苔藓"],
    tags: ["蜜感", "忍冬", "暖花", "甜感"],
    season: ["春", "夏"],
    scene: ["室内", "夜晚"],
    mood: ["松弛", "温柔"],
    longevity: 2,
    sillage: 2,
    liking: 3,
    text: "印蒿在开场带来略带野性的草本气息，迅速为香气铺开深度。忍冬与橙花的甜润花香随之浮现，像阳光下缓缓流动的花蜜，柔软而包裹。尾调的苔藓让整体变得温暖而沉静，仿佛站在一棵老树下，感受时间缓慢流淌。",
    shortFeeling: "微醺午后的花蜜",
    sceneMemory: "春天阳光下的花园",
    memoryAnchor: "等待时间的镌刻",
    imageSrc: "/images/perfume/honeysuckle_and_davana.webp",
  },
  {
    id: "xeryus-rouge",
    name: "Xeryus Rouge",
    brand: "Givenchy",
    year: "2025",
    concentration: "EDT",
    family: ["木质"],
    topNotes: ["仙人掌", "橙子", "龙蒿"],
    middleNotes: ["甜椒", "天竺葵","雪松"],
    baseNotes: ["檀香木", "雪松", "麝香"],
    tags: ["木质", "馥郁", "浓重"],
    season: ["冬", "秋"],
    scene: ["夜晚", "室内"],
    mood: ["锐利", "稳重"],
    longevity: 5,
    sillage: 4,
    liking: 4,
    text: "炽烈淡香水是一支「棱角分明」的香。名字中的「淡香水」很容易让人产生误会，事实上，浓烈的馥奇香调是这支香的核心。开场的橙子与龙蒿营造的木质香气直击喉部深处，甜椒与天竺葵在中调营造出温暖且辛辣的氛围，后调则是檀木与雪松中透出的温暖树脂感木质气息。留香时间之长可以排进我试过的香水前列。",
    shortFeeling: "冬夜里一道清冷的棱角",
    sceneMemory: "冬夜里带暖气的居室",
    memoryAnchor: "等待时间的镌刻",
    imageSrc: "/images/perfume/xeryus_rouge.webp",
  },
  {
    id: "sakura-0830",
    name: "Sakura 0830",
    brand: "My Only Fragrance",
    year: "2025",
    concentration: "EDT",
    family: ["绿叶", "木质"],
    topNotes: ["绿叶", "水生气息"],
    middleNotes: ["森林气息", "檀木"],
    baseNotes: ["干燥木质", "冷麝香"],
    tags: ["森林感", "深沉", "冷调", "潮湿"],
    season: ["春", "四季"],
    scene: ["室内", "通勤"],
    mood: ["干净", "克制"],
    longevity: 3,
    sillage: 2,
    liking: 4,
    text: "前调以浓郁的青绿气息与水生冷感展开，像潮湿空气穿过树叶时带来的清冽冲击，木质从一开始便隐约铺陈其中。随着刺激感逐渐退去，中调浮现出深沉而圆润的檀木香气，湿润而安静，仿佛走入雨后森林深处。尾调收于冷麝香与干燥木质之中，干净而悠长。",
    shortFeeling: "潮湿的雨后森林",
    sceneMemory: "雨后的森林",
    memoryAnchor: "来自姐姐的特调",
    imageSrc: "/images/perfume/sakura0830.webp",
  },
];
