import { ScentEntry } from "@/lib/types";

export const scentsTitle = "气味收藏：香气与季节";
export const scentsSubtitle = "Scent Journal";
export const scentsQuote =
  "收集并记录不同气味带来的空间感与记忆：从花香到木香，从清新到沉稳，从季节变化到时光流逝。";

export const SEASONS = ["春", "夏", "秋", "冬", "四季"] as const;
export const SCENES = ["通勤", "散步", "夜晚", "室内", "雨天"] as const;
export const FAMILIES = ["花香", "木质", "果香", "绿叶"] as const;
export const MOODS = [
  "干净",
  "放松",
  "温柔",
  "安定",
  "克制",
  "锐利",
  "治愈",
  "稳重",
] as const;

export const scentEntries: ScentEntry[] = [
  
  {
    id: "macedonia",
    name: "Macedonia",
    brand: "My Only Fragrance",
    year: "2025",
    concentration: "EDT",
    family: ["果香", "木质"],
    topNotes: ["佛手柑", "青苹果", "柠檬皮"],
    middleNotes: ["白玫瑰", "白麝香", "淡琥珀"],
    baseNotes: ["雪松木", "白麝香", "淡琥珀"],
    tags: ["干净", "自然", "通透", "空气感"],
    season: ["四季", "秋"],
    scene: ["通勤", "散步"],
    mood: ["放松", "平静","治愈"],
    longevity: 5,
    sillage: 4,
    liking: 5,
    text: "佛手柑与青苹果在开场带来清亮通透的果绿气息，像晨光穿过树叶时的第一口空气。随后柔和的白玫瑰与绿叶感缓缓浮现，让香气变得温润而自然。尾调的雪松木与白麝香轻轻铺展开来，干净、安静，仿佛阳光晒过的木地板，带着让人慢下来的温度。",
    shortFeeling: "像清晨森林里的空气，干净又温柔。",
    sceneMemory: "秋天公园里微风拂过树叶、带着干净空气的那一刻",
    memoryAnchor: "京都的冬天，清冷的空气与历史悠久的街道",
    imageSrc: "/images/perfume/macedonia.webp",
    featured: true,
  },
  {
    id: "sakura-0830",
    name: "Sakura 0830",
    brand: "My Only Fragrance",
    year: "2025",
    concentration: "EDT",
    family: ["绿叶", "木质"],
    topNotes: ["绿叶", "水生气息"],
    middleNotes: ["森林气息", "檀木"],
    baseNotes: ["干燥木质", "冷麝香"],
    tags: ["森林感", "深沉", "冷调", "潮湿"],
    season: ["春", "四季"],
    scene: ["室内", "通勤"],
    mood: ["干净", "克制"],
    longevity: 3,
    sillage: 2,
    liking: 4,
    text: "前调以浓郁的青绿气息与水生冷感展开，像潮湿空气穿过树叶时带来的清冽冲击，木质从一开始便隐约铺陈其中。随着刺激感逐渐退去，中调浮现出深沉而圆润的檀木香气，湿润而安静，仿佛走入雨后森林深处。尾调收于冷麝香与干燥木质之中，干净而悠长。",
    shortFeeling: "潮湿的雨后森林",
    sceneMemory: "雨后的森林",
    memoryAnchor: "来自姐姐的特调",
    imageSrc: "/images/perfume/sakura0830.webp",
  },
  {
    id: "willow-and-amber",
    name: "Willow & Amber",
    brand: "Jo Malone",
    year: "2026",
    concentration: "Cologne",
    family: ["木质", "琥珀", "东方"],
    topNotes: ["柳叶", "绿意", "微辛感"],
    middleNotes: ["木质调", "柔和树脂感", "轻微花感"],
    baseNotes: ["琥珀", "麝香", "温暖木香"],
    tags: ["琥珀", "温润", "安静","最近更新"],
    season: ["秋", "冬"],
    scene: ["夜晚", "室内"],
    mood: ["温暖", "沉静"],
    longevity: 3,
    sillage: 4,
    liking: 5,
    text: "柳叶与琥珀的开场是偏清透的绿意，略带一些木质的清冷感，伴随着像傍晚风吹过树叶时的轻微凉感。随后木质和琥珀慢慢铺开，气味变得柔和、温暖，像灯光照在木桌上的那种安静氛围。整体不是浓烈的琥珀，更偏‘干净的暖意’。",
    shortFeeling: "一支安静发光的琥珀木香。",
    sceneMemory: "夜晚房间里暖黄灯光照在木桌上的安静一隅",
    memoryAnchor: "等待时间的镌刻",
    imageSrc: "/images/perfume/willow-and-amber.webp",
  },
  {
    id: "english-pear-and-freesia",
    name: "English Pear & Freesia",
    brand: "Jo Malone",
    year: "2024",
    concentration: "EDC",
    family: ["果香", "花香", "木质"],
    topNotes: ["皇帝梨", "香瓜"],
    middleNotes: ["小苍兰", "玫瑰"],
    baseNotes: ["广藿香", "大黄", "麝香","琥珀"],
    tags: ["梨香", "小苍兰", "秋意", "干净"],
    season: ["春", "夏", "秋"],
    scene: ["通勤", "室内"],
    mood: ["温柔", "安定"],
    longevity: 2,
    sillage: 2,
    liking: 5,
    text: "英国梨的清甜在开场显得明亮而湿润，像雨后空气里带着果香的微凉气息。小苍兰与玫瑰在中调铺开柔软的花香层次，让香气变得轻盈而通透。尾调的麝香与琥珀轻轻收束整体轮廓，使这份清新多了一层温暖的深度，安静却耐闻。",
    shortFeeling: "像秋天午后下过雨的窗台",
    sceneMemory: "深秋雨后的图书馆",
    memoryAnchor: "新西兰冬天的雨后，带着些许泥土气息的街道",
    imageSrc: "/images/perfume/english_pear_and_freesia.webp",
  },

  {
    id: "chance-eau-tendre",
    name: "Chance Eau Fraiche",
    brand: "Chanel",
    year: "2025",
    concentration: "EDT",
    family: ["花香"],
    topNotes: ["柠檬", "雪松","香橼"],
    middleNotes: ["茉莉", "粉红胡椒", "凤眼兰"],
    baseNotes: ["广藿香", "麝香", "鸢尾花","香根草","柚木","琥珀"],
    tags: ["粉感", "干净","清新"],
    season: ["春", "四季"],
    scene: ["通勤", "室内"],
    mood: ["干净", "温柔"],
    longevity: 5,
    sillage: 4,
    liking: 4,
    text: "绿邂逅以清亮的柠檬气息开启，像清晨第一缕干净的阳光。茉莉在中调带来柔和而圆润的花香，却始终保持通透与克制，仿佛只是空气中一瞬掠过的香气。广藿香与麝香在尾调悄然铺陈，使整体变得干净而稳定，如白衬衫贴近肌肤时的安心感。",
    shortFeeling: "白衬衫与春日晨光",
    sceneMemory: "清晨空气里的露水与花香交织",
    memoryAnchor: "每当清冷的早晨总会想起的味道",
    imageSrc: "/images/perfume/chance.webp",
  },
  {
    id: "cool-water",
    name: "Cool Water",
    brand: "Davidoff",
    year: "2023",
    concentration: "EDT",
    family: ["水生", "芳香"],
    topNotes: ["薄荷", "海风感", "薰衣草"],
    middleNotes: ["檀香木", "天竺葵", "清淡花香"],
    baseNotes: ["麝香", "琥珀"],
    tags: ["清凉", "水感", "经典","最近更新"],
    season: ["夏", "四季"],
    scene: ["通勤", "雨天"],
    mood: ["清爽", "利落"],
    longevity: 3,
    sillage: 3,
    liking: 4,
    text: "冷水是很经典的清凉水生调，前调就有明显的凉感和海风感，干净、直接，不拐弯。中段带一点花香和皂感，让整体更像刚洗完澡后的清爽状态。后调是轻木质和麝香，留香不算压人，总体是清新自然的调性。",
    shortFeeling: "像一阵刚好吹过来的冷空气。",
    sceneMemory: "夏日雨后街道上的清凉空气，或高中时雨天宿舍窗外的气息",
    memoryAnchor: "高中雨天的宿舍",
    imageSrc: "/images/perfume/cool-water.webp",
  },
  {
    id: "blu-mediterraneo",
    name: "Mirto di Panarea",
    brand: "Acqua di Parma",
    year: "2024",
    concentration: "EDT",
    family: ["柑橘", "芳香"],
    topNotes: ["桃金娘", "柠檬", "罗勒"],
    middleNotes: ["海洋气息", "茉莉", "玫瑰"],
    baseNotes: ["雪松", "杜松", "琥珀"],
    tags: ["海岛", "蓝色", "通透","最近更新"],
    season: ["春", "夏"],
    scene: ["通勤", "室内"],
    mood: ["明亮", "舒展"],
    longevity: 3,
    sillage: 2,
    liking: 4,
    text: "这支的气味很有‘地中海蓝色’的画面感：前调是清亮的柑橘和柠檬香气，像阳光照在海边植物上的感觉。中段有一点柔和花香和海风的咸润感，但依然保持透明，整体并不厚重。后调的木质很轻，整体像一件干净的浅色衬衫，清爽又精致。",
    shortFeeling: "海边的午后，清爽又精致。",
    sceneMemory: "海边晴朗午后的阳光与海风",
    memoryAnchor: "等待时间的镌刻",
    imageSrc: "/images/perfume/blu-mediterraneo.webp",
  },
  {
    id: "lime-basil-and-mandarin",
    name: "Lime Basil & Mandarin",
    brand: "Jo Malone",
    year: "2026",
    concentration: "Cologne",
    family: ["柑橘", "芳香"],
    topNotes: ["青柠", "柑橘", "明亮酸感"],
    middleNotes: ["罗勒", "草本辛香", "绿色气息"],
    baseNotes: ["木质", "琥珀感", "轻麝香"],
    tags: ["青柠", "活力", "清新","最近更新"],
    season: ["春", "夏"],
    scene: ["通勤", "室内"],
    mood: ["轻快", "清醒"],
    longevity: 2,
    sillage: 3,
    liking: 4,
    text: "青柠罗勒与柑橘的前调是略带浓重馥郁的青柠和柑橘，随后散发出罗勒的草本辛香，让它不只是单纯的果香，而是更有层次、更有辨识度的馥郁香气。后调是很轻的木质和麝香，整体干净利落，营造出一种清新的氛围。",
    shortFeeling: "像一杯加了罗勒叶的冰柑橘水。",
    sceneMemory: "夏日清晨切开青柠与罗勒时的那一阵清香",
    memoryAnchor: "等待时间的镌刻",
    imageSrc: "/images/perfume/lime-basil-and-mandarin.webp",
  },
  {
    id: "oud-and-bergamot",
    name: "Oud & Bergamot",
    brand: "Jo Malone",
    year: "2026",
    concentration: "Cologne Intense",
    family: ["木质", "东方"],
    topNotes: ["佛手柑", "柑橘清苦感", "香柠檬"],
    middleNotes: ["雪松", "干燥木质", "线条感"],
    baseNotes: ["乌木", "烟熏木感", "树脂感"],
    tags: ["乌木", "深邃", "夜晚","最近更新"],
    season: ["秋", "冬"],
    scene: ["夜晚", "室内"],
    mood: ["沉稳", "神秘"],
    longevity: 4,
    sillage: 3,
    liking: 4,
    text: "乌木与佛手柑的前调是浓重厚实的乌木气息，有种置身于红木家具城中的感觉，但是更加的沉重厚实；中段是干净的雪松，把木质骨架撑起来；后调的乌木才慢慢显出来，深沉但不浑浊。",
    shortFeeling: "明亮切开深色木头的一刀。",
    sceneMemory: "深秋夜晚路灯下，深色木质的沉静",
    memoryAnchor: "等待时间的镌刻",
    imageSrc: "/images/perfume/oud-and-bergamot.webp",
  },
  
  {
    id: "wild-bluebell",
    name: "Wild Bluebell",
    brand: "Jo Malone",
    year: "2025",
    concentration: "EDC",
    family: ["绿叶", "花香"],
    topNotes: ["风铃草", "公丁香","露珠","绿叶"],
    middleNotes: ["桃子", "柿子"],
    baseNotes: ["脂粉", "麝香"],
    tags: ["透明", "林间", "皂感"],
    season: ["春", "夏"],
    scene: ["通勤", "室内"],
    mood: ["干净", "松弛"],
    longevity: 2,
    sillage: 4,
    liking: 3,
    text: "蓝风铃像一阵穿过树林的微风，带着清晨露水般的透明气息。绿叶与花香在空气中轻轻浮动，仿佛阳光洒在潮湿的土地与蓝色小花之间。整个香气始终轻盈而干净，没有刻意的浓度，只留下自然流动的清新感。",
    shortFeeling: "初夏树林间的一片蓝色",
    sceneMemory: "初夏清晨树林间沾着露珠的蓝花与绿叶",
    memoryAnchor: "等待时间的镌刻",
    imageSrc: "/images/perfume/wild_bluebell.webp",
  },
  {
    id: "english-oak-and-hazelnut",
    name: "English Oak & Hazelnut",
    brand: "Jo Malone",
    year: "2025",
    concentration: "EDC",
    family: ["木质"],
    topNotes: ["榛子"],
    middleNotes: ["雪松"],
    baseNotes: ["橡木"],
    tags: ["木质", "榛果", "温暖", "秋冬"],
    season: ["秋", "冬"],
    scene: ["室内", "夜晚"],
    mood: ["安定", "克制"],
    longevity: 2,
    sillage: 3,
    liking: 4,
    text: "榛子的开场带来柔和而饱满的木质气息，没有甜腻感，反而显得温润而安静。中调的雪松逐渐铺开干净的木香空间，像阳光落在室内木质家具上的温度。尾调的橡木让整体变得柔和而沉稳，营造出一种适合慢下来的安定氛围。",
    shortFeeling: "像是坐在壁炉旁的沙发上，温暖又舒适。",
    sceneMemory: "秋夜室内，窗外在下雨",
    memoryAnchor: "等待时间的镌刻",
    imageSrc: "/images/perfume/english_oak_and_hazelnut.webp",
  },
  {
    id: "honeysuckle-and-davana",
    name: "Honeysuckle & Davana",
    brand: "Jo Malone",
    year: "2025",
    concentration: "EDC",
    family: ["花香"],
    topNotes: ["印蒿"],
    middleNotes: ["忍冬", "橙花"],
    baseNotes: ["苔藓"],
    tags: ["蜜感", "忍冬", "暖花", "甜感"],
    season: ["春", "夏"],
    scene: ["室内", "夜晚"],
    mood: ["松弛", "温柔"],
    longevity: 2,
    sillage: 2,
    liking: 3,
    text: "印蒿在开场带来略带野性的草本气息，迅速为香气铺开深度。忍冬与橙花的甜润花香随之浮现，像阳光下缓缓流动的花蜜，柔软而包裹。尾调的苔藓让整体变得温暖而沉静，仿佛站在一棵老树下，感受时间缓慢流淌。",
    shortFeeling: "微醺午后的花蜜",
    sceneMemory: "春天阳光下的花园",
    memoryAnchor: "等待时间的镌刻",
    imageSrc: "/images/perfume/honeysuckle_and_davana.webp",
  },
  {
    id: "wood-sage-and-sea-salt",
    name: "Wood Sage & Sea Salt",
    brand: "Jo Malone",
    year: "2025",
    concentration: "Cologne",
    family: ["木质", "海盐"],
    topNotes: ["海盐感", "黄葵", "微矿物感"],
    middleNotes: ["鼠尾草", "草本", "清淡木质"],
    baseNotes: ["木质", "麝香", "琥珀感"],
    tags: ["海盐", "松弛", "高级感","最近更新"],
    season: ["春", "夏", "秋", "四季"],
    scene: ["通勤", "室内", "雨天"],
    mood: ["松弛", "通透"],
    longevity: 3,
    sillage: 2,
    liking: 5,
    text: "这支不是传统意义上很‘香’的香水，它更像一种被海风吹过的空气：有海盐的清爽感，也有鼠尾草的干净草本。前调略带海盐的刺激感，很快转为黄葵的清爽与鼠尾草的草本。木质基底很轻，不会压住前面的通透感，所以整体非常松弛、自然。",
    shortFeeling: "像海边石头缝里的风，咸一点，干净一点。",
    sceneMemory: "海边阴雨天，咸湿的风吹过礁石",
    memoryAnchor: "等待时间的镌刻",
    imageSrc: "/images/perfume/wood-sage-and-sea-sault.webp",
  },
  {
    id: "ck-be",
    name: "CK Be",
    brand: "Calvin Klein",
    year: "2023",
    concentration: "EDT",
    family: ["木质", "花香"],
    topNotes: ["香柠檬", "杜松", "薰衣草", "绿叶", "薄荷"],
    middleNotes: ["茉莉", "桃子", "青草", "兰花"],
    baseNotes: ["麝香", "檀香", "雪松"],
    tags: ["中性", "干净", "低调","最近更新"],
    season: ["四季"],
    scene: ["通勤", "室内"],
    mood: ["放松", "克制"],
    longevity: 3,
    sillage: 2,
    liking: 4,
    text: "CK Be 是很舒服的中性风格，前调是很清新的草本和柠檬香气，带有一点点的青苔感，但很快就变成柔和的麝香木质。它不强调冲击力，更像贴近皮肤的干净味道，安静、自然，适合日常高频使用。整体存在感不强，但很耐闻。",
    shortFeeling: "像一件干净的黑色棉T。",
    sceneMemory: "安静室内，阳光透过窗帘的干净一隅",
    memoryAnchor: "等待时间的镌刻",
    imageSrc: "/images/perfume/ck-be.webp",
  },
  {
    id: "white-tea",
    name: "White Tea",
    brand: "Elizabeth Arden",
    year: "2026",
    concentration: "EDT",
    family: ["茶香", "花香"],
    topNotes: ["海风", "柑橘", "清透风感"],
    middleNotes: ["马黛茶", "白鸢尾", "玫瑰"],
    baseNotes: ["麝香", "木质", "零陵香豆"],
    tags: ["白茶", "温柔", "舒缓","最近更新"],
    season: ["春", "夏", "四季"],
    scene: ["室内", "通勤"],
    mood: ["温柔", "安稳"],
    longevity: 3,
    sillage: 4,
    liking: 4,
    text: "白茶淡香水是偏柔和干净的白茶感，闻起来有一种浅色、安静、带空气感的清香。前段很轻，柔和的茶香与花香中带有丝丝的甜味；中段的花香也很克制，不会甜。后调是淡淡麝香和木质，整体像一层很薄的白色织物，温柔但有存在感。",
    shortFeeling: "安静、干净、像一杯温热的白茶。",
    sceneMemory: "清晨窗边，白茶花香的气息",
    memoryAnchor: "等待时间的镌刻",
    imageSrc: "/images/perfume/white-tea.webp",
  },
  {
    id: "xeryus-rouge",
    name: "Xeryus Rouge",
    brand: "Givenchy",
    year: "2025",
    concentration: "EDT",
    family: ["木质"],
    topNotes: ["仙人掌", "橙子", "龙蒿"],
    middleNotes: ["甜椒", "天竺葵","雪松"],
    baseNotes: ["檀香木", "雪松", "麝香"],
    tags: ["木质", "馥郁", "浓重"],
    season: ["冬", "秋"],
    scene: ["夜晚", "室内"],
    mood: ["锐利", "稳重"],
    longevity: 5,
    sillage: 4,
    liking: 3,
    text: "炽烈淡香水是一支「棱角分明」的香。名字中的「淡香水」很容易让人产生误会，事实上，浓烈的馥奇香调是这支香的核心。开场的橙子与龙蒿营造的木质香气直击喉部深处，甜椒与天竺葵在中调营造出温暖且辛辣的氛围，后调则是檀木与雪松中透出的温暖树脂感木质气息。留香时间之长可以排进我试过的香水前列。",
    shortFeeling: "冬夜里一道清冷的棱角",
    sceneMemory: "冬夜里带暖气的居室",
    memoryAnchor: "等待时间的镌刻",
    imageSrc: "/images/perfume/xeryus_rouge.webp",
  },
  {
    id: "blood-orange-and-basil",
    name: "Blood Orange & Basil",
    brand: "4711 Acqua Colonia",
    year: "2026",
    concentration: "Eau de Cologne",
    family: ["柑橘", "芳香"],
    topNotes: ["血橙", "柑橘汁感", "明亮果皮感"],
    middleNotes: ["罗勒", "绿色草本", "微微辛香"],
    baseNotes: ["清淡木质", "麝香", "干净尾调"],
    tags: ["血橙", "罗勒", "清爽"],
    season: ["春", "夏"],
    scene: ["通勤", "室内"],
    mood: ["轻快", "清醒"],
    longevity: 2,
    sillage: 2,
    liking: 4,
    text: "一上来就是很鲜明的血橙气息，带一点果汁感和果皮的清亮酸甜。罗勒的气味很快出现，把这支香从单纯果香拉回到更干净的草本方向，闻起来更加清爽、更加有层次。后调比较轻，偏贴肤，像一阵短暂但舒服的柑橘草本空气。",
    shortFeeling: "像刚切开的血橙配一片新鲜罗勒叶。",
    sceneMemory: "盛夏树荫下切开血橙、罗勒叶摆在手边的清爽瞬间",
    memoryAnchor: "大学军训时候的气味",
    imageSrc: "/images/perfume/blood-orange-and-basil.webp",
  },
  
];
